version: '3.3'
services:
  authservice:
    build: ./authservice
    volumes:
      - ./authservice:/usr/src/app
    ports:
    - "5001:80"

  scrapingservice:
    build: ./pricescraping
    volumes:
    - ./pricescraping:/usr/src/app
    ports:
    - 5002:80

  cherryprice:
    build: ./maincomponent
    volumes:
    - ./maincomponent:/usr/src/app
    ports:
    - 5000:80
    depends_on:
      - authservice
      - scrapingservice
